client_config_backend: file
client_config:
    client_id: 842946165765-g4efjj6rup23brvul02jdbold5bqbr7a.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive